name: gestanea
description: A comprehensive pregnancy and baby care mobile app.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  shared_preferences: ^2.5.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/fetus-inside-heart-shape-womb.png
  generate: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic