name: Gestanea
description: A comprehensive pregnancy and baby care mobile app.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/fetus-inside-heart-shape-womb.png
  generate: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fetus-inside-heart-shape-womb.png"
  adaptive_icon_background: "#B39DDB"
  adaptive_icon_foreground: "assets/images/fetus-inside-heart-shape-womb.png"